#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
run_name="${1:-repro_high_osi_exactcfg_current_head_$(date -u +%Y%m%dT%H%M%SZ)}"
log="$repo_root/.runs/${run_name}.log"
drive_bin="${V1_VIDEO_DRIVE_BIN:-/home/vishnu/datasets/v1_video/drives/kitti_raw_image_00_l4e_drive_40x40_128f_scale1_offset012_clip1.bin}"

if [[ ! -f "$drive_bin" ]]; then
  echo "Missing video drive binary: $drive_bin" >&2
  exit 2
fi

mkdir -p "$repo_root/.runs"

(
  set +e
  cd "$repo_root" || exit 2
  echo "RUN_NAME=$run_name"
  echo "START_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "PWD=$PWD"
  echo "GIT=$(git rev-parse --short HEAD) $(git branch --show-current)"
  echo "GPU=CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}"

  CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" \
  V1_SHEET_SIDE=40 \
  V1_VALIDATION_CORE_SIDE=32 \
  V1_L4_L23_ORIENTATION_BIAS_STRENGTH=0 \
  V1_L4_L23_ORIENTATION_NEUTRAL_DENSITY_MATCH=1 \
  V1_L23EE_LOGNORMAL_INIT=1 \
  V1_L23EE_LOGNORMAL_SIGMA=0.37 \
  V1_PERIODIC_LOCAL_GEOMETRY_ENABLE=1 \
  V1_L4_INTERSITE_ENABLE=1 \
  V1_L4_INTERSITE_EE_SCALE=0.06 \
  V1_L4_INTERSITE_E_PV_SCALE=0.03 \
  V1_L4_INTERSITE_PV_E_SCALE=0.03 \
  V1_VIDEO_REPLAY_ENABLE=1 \
  V1_VIDEO_DRIVE_BIN="$drive_bin" \
  V1_VIDEO_FRAME_COUNT=128 \
  V1_VIDEO_MAX_FRAMES=64 \
  V1_VIDEO_REPLAY_REPEAT_COUNT=3 \
  V1_VIDEO_L4_DRIVE_SCALE=0.85 \
  V1_VIDEO_FF_EVENT_TRACE_ENABLE=1 \
  V1_VIDEO_FF_EVENT_TRACE_HETERO_MINUS=0.000002 \
  V1_VIDEO_FF_HOMEOSTATIC_SCALING_ENABLE=1 \
  V1_VIDEO_FF_HOMEOSTATIC_SCALE=1.50 \
  V1_VIDEO_FF_BCM_COMPETITION_ENABLE=1 \
  V1_VIDEO_FF_BCM_COMPETITION_STRENGTH=0.25 \
  V1_VIDEO_CONSOLIDATION_ENABLE=1 \
  V1_VIDEO_CONSOLIDATION_HELDOUT_FRACTION=0.15625 \
  V1_VIDEO_RECURRENT_ONLY_CONSOLIDATION_ENABLE=1 \
  V1_VIDEO_RECURRENT_ONLY_CONSOLIDATION_PASSES=4 \
  V1_VIDEO_RECURRENT_ONLY_L23EE_STDP_AMINUS=0.000115 \
  V1_VIDEO_L23EE_TRIPLET_HOMEOSTATIC_PLASTICITY_ENABLE=1 \
  V1_VIDEO_L23EE_TRIPLET_HOMEOSTATIC_PLASTICITY_LEARNING_RATE=1.25 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_ENABLE=1 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_PV_ETA_SCALE=1.30 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_PV_TARGET_HZ=22.5 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_SECOND_ETA_SCALE=0.14 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_PV_POTENTIATION_ONLY=1 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_SOM_POTENTIATION_ONLY=1 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_TAIL_GATE_ENABLE=1 \
  V1_POST_VIDEO_INHIBITORY_STABILIZATION_TAIL_GATE_HZ=1.0 \
  V1_VIDEO_EVENT_TIMING_ENABLE=1 \
  V1_VIDEO_EVENT_REPEAT_COUNT=6 \
  V1_VIDEO_PV_RELIABILITY_OUTPUT_SCALE=1.05 \
  V1_VIDEO_SOM_RELIABILITY_OUTPUT_SCALE=0.90 \
  V1_HVA_PREDICTOR_ENABLE=0 \
  scripts/run_local_genn.sh "$run_name"

  rc=$?
  echo "END_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "RUN_RC=$rc"
  exit "$rc"
) 2>&1 | tee "$log"

exit "${PIPESTATUS[0]}"
